In [ ]:
## Numpy array and basics
# learn about numpy 

In [1]:
import numpy as np

In [2]:
# creating array from list

In [4]:
arr_1d = np.array([1,2,3,4,5]);
print("1d array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array:", arr_2d)

1d array:  [1 2 3 4 5]
2d array: [[1 2 3]
 [4 5 6]]


In [4]:
# list vs numpy array
import numpy as np
py_list = [1,2,3,4]
print("python list multiplication",py_list*2)

np_array = np.array([1,2,3]); # element wise multiplication 
print("python array multiplication",np_array*2);

import time

start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n list operation time :",time.time()-start )

start = time.time()
np_array = np.arange(10000)*2
print("\n Numpy operation time",time.time()-start)




python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
python array multiplication [2 4 6]

 list operation time : 0.0066204071044921875

 Numpy operation time 0.0010569095611572266


In [8]:
# creating array from scratch 

zeroes = np.zeros((3,4))
print("zeroes array:\n",zeroes)

ones = np.ones((2,3))
print("one array: \n",ones)

full = np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random);


sequence = np.arange(0,10,2)
print("sequence array:\n",sequence)


zeroes array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.22054614 0.22304372 0.10262501]
 [0.63853811 0.41380857 0.95025975]]
sequence array:
 [0 2 4 6 8]


In [15]:
# vector,matrix,tensor
vector = np.array([1,2,3])
print("vector",vector)

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]
                   ])
print("matrix \n",matrix)


# tensor = np.array([[[1,2], [3.4]],
#                    [[5,6],[7,8]]
#                    ])
# print("tensor",tensor);

vector [1 2 3]
matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# array properties 

arr = np.array([[1,2,3],
                [4,5,6]
                ])
print("shape",arr.shape)
print("dimension",arr.ndim)
print("size",arr.size)
print("DataType",arr.dtype)

shape (2, 3)
dimension 2
size 6
DataType int64


In [20]:
# array reshaping 

arr = np.arange(12)
print("original array",arr)

reshaped = arr.reshape((3,4));
print("reshaped \n",reshaped)

flattened = reshaped.flatten();
print("flattend array \n",flattened)


# ravel(returns view, instad of copy)
raveled = reshaped.ravel()
print("\n raveled array",raveled)


# transpose of a matrix 
transpose = reshaped.T
print("\n transposed array", transpose)


original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
