## Numpy array operations

In [1]:
import numpy as np


In [3]:
array =  np.array([1,2,3,4,5,6,7,8,9]);
print("Basic slicing",array[2:7])
print("with steps",array[1:8:2])
print("negative indexing",array[-3])


Basic slicing [3 4 5 6 7]
with steps [2 4 6 8]
negative indexing 7


In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]
                   ])
print("specific element",arr_2d[1,2])
# gives 2nd element of 1st row 
print("entire row",arr_2d[1]);
# gives entire row 

print("entire column",arr_2d[:,1])
# gives 1st column



specific element 6
entire row [4 5 6]
entire column [2 5 8]


## sorting 

In [ ]:
import numpy as np
unsorted = np.array([3,1,4,1,5,9,2,6])
print('sorted arary',np.sort(unsorted));


arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column",np.sort(arr_2d_unsorted,axis= 0))
# axis = 1 for row 


sorted arary [1 1 2 3 4 5 6 9]
sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]


## filter

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2 == 0]
print("even numbers",even_number)




even numbers [ 2  4  6  8 10]


## filter with mask 

In [ ]:
mask = numbers>5
print("numbers greater than 5 ",numbers[mask])


numbers greater than 5  [ 6  7  8  9 10]


## fancy indexing vs np.where()

In [10]:
indices = [0,2,4]
print(numbers[indices])


where_result = np.where(numbers>5)
# print(where_result)
print("Np where",numbers[where_result])

[1 3 5]
Np where [ 6  7  8  9 10]


In [13]:
condition_array = np.where(numbers>5,numbers*2,numbers)
print(condition_array)


[ 1  2  3  4  5 12 14 16 18 20]


In [ ]:
##
#samajhne ke liye 
# if(numbers>5){
#     numbers*4
# }else{
#     numbers
# }

## adding and removing data 

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,11,12,13])
# this is wrong. this will not work  
combined = arr1+arr2
print(combined)

combined1 = np.concatenate((arr1,arr2))
print(combined1)



[11 13 15 17]
[ 1  2  3  4 10 11 12 13]


## array compatiblity 

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("compatibility shapes",a.shape == b.shape)

compatibility shapes False


In [20]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print(original);
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("with new column",with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 7]
 [3 4 8]]


In [22]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("array after deletion",deleted)

array after deletion [1 2 4 5]
