## advance operation with business examples 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
sales_data = np.array([
    [1,150000,180000,220000,25000],#paradise biryani 
    [2,120000,140000,160000,190000],#beijing bytes 
    [3,200000,230000,260000,300000],# pizza hub 
    [4,180000,210000,240000,270000],# burger point 
    [5,160000,1850000,200000,230000]#chai point
])
print(sales_data)
print("===zomato sales analysis ===")
print("salses data shape",sales_data.shape)
print("\n sample data for first 3 restaurnants:",sales_data[:3])



[[      1  150000  180000  220000   25000]
 [      2  120000  140000  160000  190000]
 [      3  200000  230000  260000  300000]
 [      4  180000  210000  240000  270000]
 [      5  160000 1850000  200000  230000]]
===zomato sales analysis ===
salses data shape (5, 5)

 sample data for first 3 restaurnants: [[     1 150000 180000 220000  25000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
# total sales per year 
print(np.sum(sales_data,axis = 0))
yearLy_total = np.sum(sales_data[:,1:],axis = 0)
print(yearLy_total);


# minimum sales per restaurant 
min_sales = np.min(sales_data[:,1:],axis = 1)
print(min_sales);




[     15  810000 2610000 1080000 1015000]
[ 810000 2610000 1080000 1015000]
[ 25000 120000 200000 180000 160000]
